name: Build & Deploy QA

on:
  push:
    branches: [ "qa" ]
    paths:
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/qa.yml"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  QA_API_URL: https://qa-applicationmanager.ned-it.de

concurrency:
  group: qa-deploy
  cancel-in-progress: true

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # Owner kleinschreiben und Image-Namen im JOB setzen
      - name: Set image names
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "IMAGE_BACKEND=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/appmanager-backend" >> $GITHUB_ENV

      - name: Login to GHCR (for push)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.IMAGE_BACKEND }}:qa
            ${{ env.IMAGE_BACKEND }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      # Owner kleinschreiben und Image-Namen im JOB setzen
      - name: Set image names
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
          echo "IMAGE_FRONTEND=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/appmanager-frontend" >> $GITHUB_ENV

      - name: Login to GHCR (for push)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          build-args: |
            API_PUBLIC_URL=${{ env.QA_API_URL }}
          tags: |
            ${{ env.IMAGE_FRONTEND }}:qa
            ${{ env.IMAGE_FRONTEND }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

    deploy-qa:
    needs: [ build-backend, build-frontend ]
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy with health check & auto-rollback
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          REGISTRY_USER: ${{ secrets.REGISTRY_USER }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
          QA_URL: ${{ env.QA_API_URL }}
          OWNER_RAW: ${{ github.repository_owner }}
        run: |
          ssh -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "
            set -e

            OWNER_LC=\$(echo \"$OWNER_RAW\" | tr '[:upper:]' '[:lower:]')
            COMPOSE='/srv/docker/qa/applicationmanager/compose/docker-compose.qa.yml'

            # Vorherige laufende Image-IDs sichern (für Rollback)
            PREV_BACKEND=\$(docker inspect -f '{{.Image}}' qa-appmanager-backend 2>/dev/null || true)
            PREV_FRONTEND=\$(docker inspect -f '{{.Image}}' qa-appmanager-frontend 2>/dev/null || true)
            echo \"Prev: BACKEND=\$PREV_BACKEND FRONTEND=\$PREV_FRONTEND\"

            # Login & reguläres Update
            echo \$GHCR_TOKEN | docker login ghcr.io -u \"\$REGISTRY_USER\" --password-stdin
            docker compose -f \"\$COMPOSE\" pull
            docker compose -f \"\$COMPOSE\" up -d

            # Externe Healthchecks (mehrfach versuchen)
            ok_backend=false
            ok_front=false
            for i in 1 2 3 4 5 6; do
              if curl -fsS \"${QA_URL}/api/health\" | grep -q '\"status\":\"ok\"'; then ok_backend=true; fi
              if curl -fsSI \"${QA_URL}/\" | head -n1 | grep -q '200'; then ok_front=true; fi
              \$ok_backend && \$ok_front && break
              sleep 5
            done

            if ! \$ok_backend || ! \$ok_front; then
              echo 'Deploy unhealthy -> ROLLBACK'

              # :qa lokal auf frühere Images retaggen
              if [ -n \"\$PREV_BACKEND\" ]; then docker tag \"\$PREV_BACKEND\" ghcr.io/\$OWNER_LC/appmanager-backend:qa; fi
              if [ -n \"\$PREV_FRONTEND\" ]; then docker tag \"\$PREV_FRONTEND\" ghcr.io/\$OWNER_LC/appmanager-frontend:qa; fi

              # Wichtig: beim Rollback kein Pull erzwingen (override pull_policy)
              docker compose -f \"\$COMPOSE\" up -d --no-build --no-deps --pull never qa-appmanager-backend qa-appmanager-frontend

              exit 1  # Job rot markieren
            fi

            echo 'Deploy healthy'
          "
